### ISSUE TITLE
Max value size on HangfireSet

### ISSUE THREAD

**Issue by jack775544** [sergezhigunov/Hangfire.EntityFrameworkCore#16]
I have been using this library together with [Hangfire.Console](https://github.com/pieceofsummer/Hangfire.Console) and have come across a limitation with the value size in the HangfireSet table. The console library will store values in HangfireSet and the current schema that is defined has a [max size of 100](https://github.com/sergezhigunov/Hangfire.EntityFrameworkCore/blob/main/src/Hangfire.EntityFrameworkCore/HangfireSet.cs#L11). This makes it frustrating since it means that the max size of a of a log message is 100 characters long, not very large at all!

I propose that the MaxLength on HangfireSet is either removed or at least increased to 256 to match the value that is set in the SQL Server storage.

Happy to make a PR for this you agree with the changes.

**Comment by jack775544** [comment]
Looking into this one a little more and it seems someone has already had this issue in the past https://github.com/pieceofsummer/Hangfire.Console/issues/93

**Comment by sergezhigunov** [comment]
Hi @jack775544. I suppose that removing length restrictions on columns that are part of indices is a breaking change for some databases, for example Oracle. So the only thing we can do at the moment in these cases is increase the limits.

I would be glad if you increase the size of `HangfireSet` ->` Key`.
You can also increase the limits up to 256 for the following columns:
- `HangfireCounter` -> `Key`
- `HangfireHash` -> `Key`
- `HangfireHash` -> `Field`
- `HangfireJob` -> `StateName`
- `HangfireJobParameter` -> `Name`
- `HangfireList` -> `Key`
- `HangfireLock` -> `Id`
- `HangfireQueuedJob` -> `Queue`
- `HangfireServer` -> `Id`
- `HangfireSet` -> `Value`
- `HangfireState` -> `Name`
- `HangfireState` -> `Reason` (in this case, you can remove the length constraint because the column doesn't participate in any indices).

Thank you in advance.

**Comment by jack775544** [comment]
Sounds good, I will submit a PR for it.
