### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by adamhathcock** [sergezhigunov/Hangfire.EntityFrameworkCore#9]
This looks interesting and a bit active.  With the churn on dotnet 5 and be using a non-official hangfire storage, an EFCore solution would be better.

Does this work well?  What issues do you have?  I don't mind helping out on some outstanding work if there's any.

**Comment by sergezhigunov** [comment]
Yes, this is well tested and appears to be in some demand.
However, EFCore has several limitations that force you to choose for provider-specific implementations like [Hangfire.SqlServer](https://www.nuget.org/packages/Hangfire.SqlServer/), [Hangfire.PostgreSql](https://www.nuget.org/packages/Hangfire.PostgreSql/) and some others. For example, using optimistic concurrency when [capturing a queue item](https://github.com/sergezhigunov/Hangfire.EntityFrameworkCore/blob/master/src/Hangfire.EntityFrameworkCore/EFCoreJobQueue.cs#L60) is not as performant as when using [an update query that returns output](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerJobQueue.cs#L169). There is a related issue #3.
Another issue #1 is that EFCore uses provider-specific migrations by design and it is quite problematic to create provider-neutral migrations.
And the next issue #2 is that most Hangfire queue implementations depend on [Hangfire.SqlServer](https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/IPersistentJobQueue.cs#L26), where the queue service interface depends on TFM, which can lead to non-obvious consequences in complex dependency graphs.
I will be glad for any help or idea, if you have something. Thank you in advance.
